name: ci/cd workflow
 
on:
 push:
   branches:
     - main
     - features/*
 pull_request:
 
jobs:
 tests:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       php: [8.1]
 
   name: Test - PHP ${{ matrix.php }}
 
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Cache PHP dependencies
       uses: actions/cache@v1
       with:
         path: vendor
         key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
 
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php }}
         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
         coverage: none
 
     - name: Copy ENV Laravel Configuration for CI
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
 
     - name: Install dependencies
       run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

     - name: Generate app key
       run: php artisan key:generate
 
     - name: Run migrations
       run: php artisan migrate
 
     - name: Optimize app
       run: php artisan optimize

     - name: Dump autoload
       run: composer dump

     - name: Execute tests
       run: php artisan test
       env:
         APP_ENV: local
         APP_URL: "http://127.0.0.1:8000"
         DB_CONNECTION: mysql
         DB_DATABASE: ZIPCODESDB
         DB_PORT: ${{ job.services.mysql.ports[3306] }}
         DB_USER: root
